version: '3.6'

services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:latest"
    volumes:
      - /var/lib/docker/data/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /dev:/dev
    restart: unless-stopped
    privileged: true
    network_mode: host
  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    restart: always
    environment:
      - TZ=Europe/London
    ports:
      - "1880:1880"
      - "502:502"
      - "11502:11502"
    volumes:
      - /var/lib/docker/data/nod-red:/data
      - /dev:/dev 
    privileged: true 
  influxdb:
    image: influxdb:latest #arm64v8/influxdb:2.0 
    container_name: influxdb
    restart: always
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    ports:
      - '8086:8086'
    volumes:
      - /var/lib/docker/data/influxdata:/var/lib/influxdb
  influxdb_cli:
    links:
      - influxdb
    image: influxdb:latest
    volumes:
      # Mount for influxdb data directory and configuration
      - /var/lib/docker/data/influxdb
    environment: 
       # Use these same configurations parameters in your telegraf configuration, mytelegraf.conf.
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminadmin
      - DOCKER_INFLUXDB_INIT_ORG=myorg
      - DOCKER_INFLUXDB_INIT_BUCKET=mybucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    depends_on:
      - influxdb
  grafana:
    image: grafana/grafana
    user: "0" 
    container_name: grafana-server
    restart: always
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
      - GF_AUTH_ANONYMOUS_ENABLED=true
    links:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - /var/lib/docker/data/grafanadata:/var/lib/grafana

  esphome:
    container_name: esphome
    image: ghcr.io/esphome/esphome
    volumes:
      - /var/lib/docker/data/esphome/config:/config
    restart: always
    privileged: true
    network_mode: host

    environment:
      - ESPHOME_DASHBOARD_USE_PING=true
      - USERNAME=esphome
      - PASSWORD=esphome
  python_app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - '8888:8888'
    depends_on:
      - influxdb
networks:
  app: